# ######################################################################################################################
# SUPPLIERS
# ######################################################################################################################

### get all suppliers
GET {{baseURL}}/supplier/readAll.php
Accept: application/json

### edit a supplier
PUT {{baseURL}}/supplier/update.php
Content-Type: application/json

{
  "id" : "1",
  "name" : "sin proveedor"
}

### create a new supplier
POST {{baseURL}}/supplier/create.php
Content-Type: application/json

{
  "name" : "gatto"
}

###
# ######################################################################################################################
# PRODUCTS
# ######################################################################################################################

### get all products by supplier id and period id
GET {{baseURL}}/product/read.php?supplier_id=2&period_id=1
Accept: application/json

### update a product with new quantities
PUT {{baseURL}}/product/update.php
Content-Type: application/json

{
  "id" : "9374",
  "deposit" : "10",
  "outflow0" : "2",
  "outflow1" : "4",
  "left" : "6",
  "userId" : 1,
  "lastOperation" : "Valeria ha sottratto un cuore"
}

### search a product
POST {{baseURL}}/product/search.php
Content-Type: application/json

{
  "query" : "salsa",
  "period" : "1"
}

### delete a product
DELETE {{baseURL}}/controllers/product.php
Content-Type: application/json

{
  "id": 34
}

### create a new product with default category and in the last period
POST {{baseURL}}/controllers/product.php
Content-Type: application/json

{
  "name": "product name",
  "supplier": 2,
  "unit": "product unit",
  "note": "note"
}

### modify a product
PUT {{baseURL}}/controllers/product.php
Content-Type: application/json

{
  "id": 30,
  "name": "product name",
  "supplier": 2,
  "unit": "product unit",
  "note": "note"
}

### get all products in the last period
GET {{baseURL}}/controllers/product.php

###
# ######################################################################################################################
# PERIODS
# ######################################################################################################################

### get last period
GET {{baseURL}}/period/readLast.php
Accept: application/json

### create a new period
POST {{baseURL}}/period/create.php

### get previous period
GET {{baseURL}}/period/previous.php?id=19
Accept: application/json

### get next period
GET {{baseURL}}/period/next.php?id=19
Accept: application/json

### get all periods
GET {{baseURL}}/period/readAll.php

### delete a period
DELETE {{baseURL}}/period/delete.php?id=3

###
# ######################################################################################################################
# OPERATIONS
# ######################################################################################################################

### get all operations
GET {{baseURL}}/operation/readAll.php

###
# ######################################################################################################################
# USER
# ######################################################################################################################

### get user info
GET {{baseURL}}/user/read.php?id=1

